fastlane_version "2.52.0"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
    # carthage(cache_builds: true)
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  lane :development do
    match(type: "development")
    gym(scheme: "Alex map app", export_method: "development")
  end

  lane :alpha do
    increment_build_number
    match(type: "adhoc", app_identifier: "com.rep.Alex-map-app.alpha")
    gym(scheme: "Alex map app", export_method: "ad-hoc", configuration: "Alpha")
    crashlytics(
      api_token: "002d1e80e7bf3a300de583f69a92347342fc38a9",
      build_secret: "e3df1c13235f9dab0dc7accc866329608184f2134ce261febd9bf33b9940b592",
      groups: "Rep"
   )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Native punch tracker") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
